[platformio]
default_envs = teensy_master

[common]
monitor_speed = 115200
lib_deps =

[env:teensy_master]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = ${common.monitor_speed}
build_src_filter =
  +<teensy_master/>

[env:pico_loadcell]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = ${common.monitor_speed}
build_src_filter =
  +<pico_loadcell/>
build_flags =
  -D HAPTIC_MODULE_KIND=MODULE_KIND_LOADCELL
  -D HAPTIC_I2C_ADDRESS=0x20

[env:pico_pressure]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = ${common.monitor_speed}
build_src_filter =
  +<pico_pressure/>
build_flags =
  -D HAPTIC_MODULE_KIND=MODULE_KIND_PRESSURE
  -D HAPTIC_I2C_ADDRESS=0x21

[env:pico_encoder]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = ${common.monitor_speed}
build_src_filter =
  +<pico_encoder/>
build_flags =
  -D HAPTIC_MODULE_KIND=MODULE_KIND_ENCODER
  -D HAPTIC_I2C_ADDRESS=0x22
